steps:
  - label: ':robot_face: Android Build'
    command:
      - 'curl https://sh.rustup.rs -sSf | sh -s -- -y'
      - 'yarn cleaninstall --frozen-lockfile --skip-optional --network-timeout 180000'
      - 'cd native/android'
      - './gradlew bundleRelease --no-daemon "-Dorg.gradle.jvmargs=-Xmx32g -XX:MaxPermSize=32g -XX:+HeapDumpOnOutOfMemoryError"'
    plugins:
      - docker#v3.13.0:
          image: 'reactnativecommunity/react-native-android:latest'
          environment:
            - 'BUILDKITE=true'
    agents:
      - 'autoscaling=true'
