[package]
name = "opaque-ke-node"
version = "0.1.0"
description = "Exposes the opaque-ke Rust library to Node"
license = "BSD-3-Clause"
edition = "2021"
exclude = ["index.node"]

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.3"
opaque-ke = "1.2"
curve25519-dalek = "3.2"
rand = "0.8"
sha2 = "0.9"
digest = "0.9"

[dependencies.neon]
version = "0.10"
default-features = false
features = ["napi-6"]
