name: ShellCheck

on:
  push:
    branches: [master]

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2

      - name: Set globstar
        run: shopt -s globstar

      - name: Run ShellCheck
        run: shellcheck -x -P SCRIPTDIR **/*.sh
